### ISSUE TITLE
Search option in header

### ISSUE THREAD

**Issue by zugspitze** [Anna-Arteeva/HB-front#1]
Currently the header is missing search option. Some search options like Strava would be cool but not necessary. 

![Screen Shot 2019-08-28 at 15 04 53](https://user-images.githubusercontent.com/12557673/63858125-3f484b00-c9a5-11e9-8258-71bf1f19dcc1.png)

**Comment by zugspitze** [comment]
It's not so important for the homepage, since we already have a search functionality there. But for other pages it would be useful. If this search looks complicated, you can put a simple input, and we can enhance it later.

**Comment by Anna-Arteeva** [comment]
I added a simple search input there for now. Can hide it for the homepage.

**Comment by zugspitze** [comment]
Thanks 👍
