### ISSUE TITLE
Responsiveness in small devices (mobile, iPad)

### ISSUE THREAD

**Issue by zugspitze** [Anna-Arteeva/HB-front#3]
Some part of the page (especially last section), doesn't look responsive in iPad Pro. Please check the picture below:
![Screen Shot 2019-08-28 at 15 13 20](https://user-images.githubusercontent.com/12557673/63858828-7ff49400-c9a6-11e9-9ba9-08e274d18e1a.png)

**Comment by Anna-Arteeva** [comment]
Is it still the case? Looks fine to me

**Comment by zugspitze** [comment]
Fixed, thanks 👍
