### ISSUE TITLE
User info in the header 

### ISSUE THREAD

**Issue by zugspitze** [Anna-Arteeva/HB-front#5]
Please add also some info for logged in member in the header, something like:
![Screen Shot 2019-08-29 at 11 45 29](https://user-images.githubusercontent.com/12557673/63929946-a112be80-ca52-11e9-9168-b643b4b9229b.png)

**Comment by zugspitze** [comment]
If you could simply add this information in the nav bar, I can implement the logic.

**Comment by Anna-Arteeva** [comment]
It's already there, except for the search input. But just use simple input, I will fix the styles and markup later. Same with responsiveness - you can already do the logic and I will fix the visual appearance later
